import { Cpu, Activity, Droplets, Info } from 'lucide-react';

export function HardwareStatus() {
  return (
    <div className="bg-[#0D1422] border border-slate-800 rounded-2xl flex flex-col h-full shadow-sm">
      <div className="p-5 border-b border-slate-800 flex items-center justify-between">
        <h3 className="text-white font-bold uppercase text-xs tracking-widest">System Architecture Status</h3>
      </div>
      
      <div className="p-5">
        <div className="bg-amber-500/10 border border-amber-500/20 rounded-lg p-3 mb-5 flex items-start">
          <Info className="w-4 h-4 text-amber-500 mt-0.5 mr-3 shrink-0" />
          <div>
            <div className="text-xs font-bold text-amber-500 tracking-wider mb-1">SIMULATION MODE</div>
            <p className="text-[11px] text-amber-500/80 leading-relaxed">
              Physical sensors are not connected yet. Values shown are generated by the prototype simulation engine.
            </p>
          </div>
        </div>

        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-3">
              <div className="bg-slate-800/50 p-2 rounded">
                <Cpu className="w-4 h-4 text-slate-400" />
              </div>
              <div>
                <div className="text-sm font-semibold text-slate-200">ESP32 Gateway</div>
                <div className="text-[10px] text-slate-500 tracking-wide mt-0.5">Hardware integration pending</div>
              </div>
            </div>
            <div className="flex items-center space-x-1.5">
              <div className="w-1.5 h-1.5 rounded-full bg-slate-600"></div>
              <span className="text-[10px] font-bold text-slate-500 tracking-wider">NOT CONNECTED</span>
            </div>
          </div>

          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-3">
              <div className="bg-cyan-500/10 p-2 rounded border border-cyan-500/20">
                <Activity className="w-4 h-4 text-cyan-400" />
              </div>
              <div>
                <div className="text-sm font-semibold text-slate-200">MPU6050 #1</div>
                <div className="text-[10px] text-slate-500 tracking-wide mt-0.5">Primary Accelerometer</div>
              </div>
            </div>
            <div className="flex items-center space-x-1.5">
              <div className="w-1.5 h-1.5 rounded-full bg-cyan-400 animate-pulse"></div>
              <span className="text-[10px] font-bold text-cyan-400 tracking-wider">SIMULATED</span>
            </div>
          </div>

          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-3">
              <div className="bg-cyan-500/10 p-2 rounded border border-cyan-500/20">
                <Activity className="w-4 h-4 text-cyan-400" />
              </div>
              <div>
                <div className="text-sm font-semibold text-slate-200">MPU6050 #2</div>
                <div className="text-[10px] text-slate-500 tracking-wide mt-0.5">Secondary Accelerometer</div>
              </div>
            </div>
            <div className="flex items-center space-x-1.5">
              <div className="w-1.5 h-1.5 rounded-full bg-cyan-400 animate-pulse"></div>
              <span className="text-[10px] font-bold text-cyan-400 tracking-wider">SIMULATED</span>
            </div>
          </div>

          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-3">
              <div className="bg-cyan-500/10 p-2 rounded border border-cyan-500/20">
                <Droplets className="w-4 h-4 text-cyan-400" />
              </div>
              <div>
                <div className="text-sm font-semibold text-slate-200">DHT11</div>
                <div className="text-[10px] text-slate-500 tracking-wide mt-0.5">Environmental Sensor</div>
              </div>
            </div>
            <div className="flex items-center space-x-1.5">
              <div className="w-1.5 h-1.5 rounded-full bg-cyan-400 animate-pulse"></div>
              <span className="text-[10px] font-bold text-cyan-400 tracking-wider">SIMULATED</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
